In [116]:
# Tentukan Library Yang Digunakan
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [117]:
# Load Dataset
gaji_dataset = pd.read_csv("data-gaji.csv")

In [118]:
gaji_dataset.head(5)

Gaji Bulan Desember  Menerima  Tanggungan  GENDER  Status Penerima Bantuan
0               500000    300000           2       0                        1
1              3900000         0           4       1                        0
2              4600000         0           4       1                        0
3               750000         0           2       1                        0
4               300000    300000           2       0                        1

In [119]:
gaji_dataset.shape

(150, 5)

In [120]:
gaji_dataset['Status Penerima Bantuan'].value_counts()

Status Penerima Bantuan
0    99
1    51
Name: count, dtype: int64

In [121]:
# Memisahkan Data Dan Label
X = gaji_dataset.drop(columns='Status Penerima Bantuan', axis=1)
Y = gaji_dataset['Status Penerima Bantuan']

In [122]:
print(X)

     Gaji Bulan Desember  Menerima  Tanggungan  GENDER
0                 500000    300000           2       0
1                3900000         0           4       1
2                4600000         0           4       1
3                 750000         0           2       1
4                 300000    300000           2       0
..                   ...       ...         ...     ...
145               770000         0           2       1
146               645500    300000           2       1
147               520000    300000           2       1
148              4000000         1           2       1
149              5200000         1           1       0

[150 rows x 4 columns]


In [123]:
print(Y)

0      1
1      0
2      0
3      0
4      1
      ..
145    0
146    1
147    1
148    0
149    0
Name: Status Penerima Bantuan, Length: 150, dtype: int64


In [124]:
# Standarisasi Data
scaler = StandardScaler()

In [125]:
scaler.fit(X)

StandardScaler()

In [126]:
standarized_data = scaler.transform(X)

In [127]:
print(standarized_data)

[[-0.7747868   1.37281295 -0.19778727 -1.05483461]
 [ 0.88590883 -0.72843307  2.27455361  0.94801592]
 [ 1.22781675 -0.72843307  2.27455361  0.94801592]
 [-0.65267683 -0.72843307 -0.19778727  0.94801592]
 [-0.87247478  1.37281295 -0.19778727 -1.05483461]
 [ 0.44631293 -0.72843307  1.03838317 -1.05483461]
 [ 0.78822085 -0.72843307  1.03838317  0.94801592]
 [ 1.08128479 -0.72843307 -1.43395771  0.94801592]
 [-0.75036481  1.37281295  1.03838317 -1.05483461]
 [-0.79920879  1.37281295 -1.43395771 -1.05483461]
 [-0.79920879  1.37281295 -0.19778727 -1.05483461]
 [-0.79920879  1.37281295 -0.19778727 -1.05483461]
 [ 0.88590883 -0.72843307 -1.43395771  0.94801592]
 [ 1.71625664 -0.72843307 -0.19778727 -1.05483461]
 [-0.84805278  1.37281295 -1.43395771  0.94801592]
 [-0.75036481  1.37281295 -0.19778727 -1.05483461]
 [-0.7747868   1.37281295 -0.19778727 -1.05483461]
 [ 1.9116326  -0.72843307 -1.43395771  0.94801592]
 [ 1.61856866 -0.72843307 -0.19778727 -1.05483461]
 [ 2.10700856 -0.72843307 -1.43

In [128]:
X = standarized_data
Y = gaji_dataset['Status Penerima Bantuan']

In [129]:
print(X)
print(Y)

[[-0.7747868   1.37281295 -0.19778727 -1.05483461]
 [ 0.88590883 -0.72843307  2.27455361  0.94801592]
 [ 1.22781675 -0.72843307  2.27455361  0.94801592]
 [-0.65267683 -0.72843307 -0.19778727  0.94801592]
 [-0.87247478  1.37281295 -0.19778727 -1.05483461]
 [ 0.44631293 -0.72843307  1.03838317 -1.05483461]
 [ 0.78822085 -0.72843307  1.03838317  0.94801592]
 [ 1.08128479 -0.72843307 -1.43395771  0.94801592]
 [-0.75036481  1.37281295  1.03838317 -1.05483461]
 [-0.79920879  1.37281295 -1.43395771 -1.05483461]
 [-0.79920879  1.37281295 -0.19778727 -1.05483461]
 [-0.79920879  1.37281295 -0.19778727 -1.05483461]
 [ 0.88590883 -0.72843307 -1.43395771  0.94801592]
 [ 1.71625664 -0.72843307 -0.19778727 -1.05483461]
 [-0.84805278  1.37281295 -1.43395771  0.94801592]
 [-0.75036481  1.37281295 -0.19778727 -1.05483461]
 [-0.7747868   1.37281295 -0.19778727 -1.05483461]
 [ 1.9116326  -0.72843307 -1.43395771  0.94801592]
 [ 1.61856866 -0.72843307 -0.19778727 -1.05483461]
 [ 2.10700856 -0.72843307 -1.43

In [130]:
# Memisahkan Data Training Dan Data Testing
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [131]:
print(X.shape, X_train.shape, X_test.shape)

(150, 4) (120, 4) (30, 4)


In [132]:
# Membuat Data Latih Menggunakan Algoritma SVM
classifier = svm.SVC(kernel='linear')

In [133]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [134]:
# Membuat Evaluasi Unutuk Mengukur Tingkat Akurasi 
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [135]:
print('Akurasi Data Training Adalah = ', training_data_accuracy)

Akurasi Data Training Adalah =  0.9916666666666667


In [136]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [139]:
print('Akurasi Data Testing Adalah = ', test_data_accuracy)

Akurasi Data Testing Adalah =  1.0


In [140]:
# Membuat Model Prediksi
input_data = (500000, 300000, 2, 0)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if prediction[0] == 0:
    print('Tidak Menerima')
else:
    print('Terima Bantuan')

[[-0.7747868   1.37281295 -0.19778727 -1.05483461]]
[1]
Terima Bantuan


In [141]:
# Simpan Model
import pickle

In [142]:
filename = 'gaji_model.sav'
pickle.dump(classifier, open(filename,'wb'))